package com.nona.annotation;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks a type as generated by the projectScaffolding scaffold template.
 * <p>
 * Retained only at compile time ({@link RetentionPolicy#SOURCE}) to
 * serve as documentation and tooling hint, with zero runtime overhead.
 *
 * @author nona
 */
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.SOURCE)
public @interface ScaffoldGenerated {
}
